CREATE TABLE gastos (
    id SERIAL PRIMARY KEY,
    gasto VARCHAR(255) NOT NULL,
    monto NUMERIC(10, 2) NOT NULL,
    categoria VARCHAR(100),
    medio_pago VARCHAR(50),
    mes INTEGER NOT NULL,
    year INTEGER NOT NULL,
    cuota_actual INTEGER DEFAULT 1,
    cuotas_totales INTEGER DEFAULT 1,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ingresos (
    id SERIAL PRIMARY KEY,
    monto NUMERIC(10, 2) NOT NULL,
    origen VARCHAR(255),
    mes INTEGER NOT NULL,
    year INTEGER NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);